/**
 * Constants and translations for Accountant Team Module
 */

import { TaskTemplate } from "./types";

export const DICTIONARY = {
  PL: {
    dashboard: "Pulpit",
    tasks: "Zadania",
    calendar: "Kalendarz",
    chat: "Komunikator",
    documents: "Dokumenty",
    settings: "Ustawienia",
    team: "Drużyna",
    profile: "Mój Profil",
    new_task: "Nowe Zadanie",
    edit_task: "Edytuj Zadanie",
    search: "Szukaj...",
    todo: "Do Zrobienia",
    in_progress: "W Trakcie",
    review: "Do Sprawdzenia",
    done: "Zakończone",
    dueDate: "Termin",
    dueTime: "Godzina",
    assignee: "Przypisany",
    priority: "Priorytet",
    send: "Wyślij",
    upcoming_deadlines: "Nadchodzące Terminy",
    welcome: "Witaj w Drużynie Księgowych",
    users_online: "Księgowi Online",
    upload_doc: "Dodaj Dokument",
    my_tasks: "Moje Zadania",
    all_tasks: "Wszystkie",
    save_changes: "Zapisz Zmiany",
    delete_task: "Usuń Zadanie",
    cancel: "Anuluj",
    full_name: "Imię i Nazwisko",
    role: "Rola",
    contact_email: "Email Kontaktowy",
    team_members: "Członkowie Zespołu",
    quick_templates: "Szybkie Szablony",
    client_name: "Nazwa Klienta",
    period: "Okres",
    year: "Rok",
    title: "Tytuł",
    description: "Opis",
    status: "Status",
    move_to: "Przenieś do",
    create_template: "Zarządzaj Szablonami",
    template_name: "Nazwa Szablonu",
    template_desc: "Opis",
    save_template: "Zapisz Szablon",
    manage_templates: "Menadżer Szablonów",
    add_new_template: "Dodaj Nowy Szablon",
    system_template: "Wszystkie Szablony",
    custom_template: "Szablon Własny",
    select_color: "Wybierz Kolor",
    edit: "Edytuj",
    delete: "Usuń",
    category: "Kategoria",
    estimated_hours: "Estymowany Czas (h)",
    cat_tax: "Podatki",
    cat_payroll: "Kadry/Płace",
    cat_audit: "Audyt",
    cat_meeting: "Spotkanie",
    cat_advisory: "Doradztwo",
    cat_general: "Ogólne",
    attachments: "Załączniki",
    add_attachment: "Dodaj plik",
    record_voice: "Nagraj notatkę",
    stop_recording: "Zatrzymaj",
    recording: "Nagrywanie...",
    drop_files: "Upuść pliki tutaj",
    voice_note: "Notatka Głosowa",
    new_group: "Nowa Grupa",
    group_name: "Nazwa Grupy",
    create_group: "Utwórz Grupę",
    search_messages: "Szukaj w czacie...",
    overdue: "Przeterminowane",
    high_priority: "Wysoki Priorytet",
    team_workload: "Obciążenie Zespołu",
    task_distribution: "Status Zadań",
    recent_activity: "Ostatnia Aktywność",
    quick_actions: "Szybkie Akcje",
    view_calendar: "Zobacz Kalendarz",
    next_deadline: "Najbliższy Termin",
    days_left: "dni do końca",
    phone: "Telefon",
    website: "Strona WWW",
    location: "Lokalizacja",
    about: "O mnie",
    meet_team: "Poznaj drużynę księgowych",
    invite_accountant: "Zaproś księgowego",
    pending_invites: "Oczekujące zaproszenia",
    my_groups: "Moje Grupy",
    all_accountants: "Wszyscy Księgowi",
    create_new_group: "Utwórz nową grupę",
    group_description: "Opis grupy",
    members: "Członkowie",
    invite_to_group: "Zaproś do grupy",
    leave_group: "Opuść grupę",
    delete_group: "Usuń grupę",
    back_to_main: "Wróć do panelu głównego",
    week: "Tydzień",
    select_week: "Wybierz Tydzień",
    // Additional translations for components
    add_task: "Dodaj zadanie",
    search_tasks: "Szukaj zadań...",
    all_statuses: "Wszystkie statusy",
    low: "Niski",
    medium: "Średni",
    high: "Wysoki",
    urgent: "Pilny",
    due_date: "Termin",
    save: "Zapisz",
    invite_member: "Zaproś członka",
  },
  NL: {
    dashboard: "Dashboard",
    tasks: "Taken",
    calendar: "Kalender",
    chat: "Chat",
    documents: "Documenten",
    settings: "Instellingen",
    team: "Team",
    profile: "Mijn Profiel",
    new_task: "Nieuwe Taak",
    edit_task: "Taak Bewerken",
    search: "Zoeken...",
    todo: "Te Doen",
    in_progress: "Bezig",
    review: "Nazien",
    done: "Klaar",
    dueDate: "Deadline",
    dueTime: "Tijd",
    assignee: "Toegewezen aan",
    priority: "Prioriteit",
    send: "Verstuur",
    upcoming_deadlines: "Komende Deadlines",
    welcome: "Welkom bij Team Boekhouders",
    users_online: "Boekhouders Online",
    upload_doc: "Upload Document",
    my_tasks: "Mijn Taken",
    all_tasks: "Alle",
    save_changes: "Wijzigingen Opslaan",
    delete_task: "Taak Verwijderen",
    cancel: "Annuleren",
    full_name: "Volledige Naam",
    role: "Rol",
    contact_email: "Contact E-mail",
    team_members: "Teamleden",
    quick_templates: "Snelle Sjablonen",
    client_name: "Klantnaam",
    period: "Periode",
    year: "Jaar",
    title: "Titel",
    description: "Omschrijving",
    status: "Status",
    move_to: "Verplaats naar",
    create_template: "Sjablonen Beheren",
    template_name: "Sjabloonnaam",
    template_desc: "Omschrijving",
    save_template: "Sjabloon Opslaan",
    manage_templates: "Sjabloonbeheer",
    add_new_template: "Nieuw Sjabloon Toevoegen",
    system_template: "Alle Sjablonen",
    custom_template: "Aangepast Sjabloon",
    select_color: "Kies Kleur",
    edit: "Bewerken",
    delete: "Verwijderen",
    category: "Categorie",
    estimated_hours: "Geschatte Uren",
    cat_tax: "Belasting",
    cat_payroll: "Salaris",
    cat_audit: "Audit",
    cat_meeting: "Vergadering",
    cat_advisory: "Advies",
    cat_general: "Algemeen",
    attachments: "Bijlagen",
    add_attachment: "Bestand Toevoegen",
    record_voice: "Spraaknotitie",
    stop_recording: "Stoppen",
    recording: "Opnemen...",
    drop_files: "Bestanden hier neerzetten",
    voice_note: "Spraaknotitie",
    new_group: "Nieuwe Groep",
    group_name: "Groepsnaam",
    create_group: "Groep Maken",
    search_messages: "Zoek in chat...",
    overdue: "Te Laat",
    high_priority: "Hoge Prioriteit",
    team_workload: "Teamwerkbelasting",
    task_distribution: "Taakverdeling",
    recent_activity: "Recente Activiteit",
    quick_actions: "Snelle Acties",
    view_calendar: "Bekijk Kalender",
    next_deadline: "Volgende Deadline",
    days_left: "dagen over",
    phone: "Telefoon",
    website: "Website",
    location: "Locatie",
    about: "Over mij",
    meet_team: "Ontmoet het boekhouders team",
    invite_accountant: "Boekhouder uitnodigen",
    pending_invites: "Openstaande uitnodigingen",
    my_groups: "Mijn Groepen",
    all_accountants: "Alle Boekhouders",
    create_new_group: "Nieuwe groep maken",
    group_description: "Groepsbeschrijving",
    members: "Leden",
    invite_to_group: "Uitnodigen voor groep",
    leave_group: "Groep verlaten",
    delete_group: "Groep verwijderen",
    back_to_main: "Terug naar hoofdpaneel",
    week: "Week",
    select_week: "Selecteer Week",
    // Additional translations for components
    add_task: "Taak toevoegen",
    search_tasks: "Taken zoeken...",
    all_statuses: "Alle statussen",
    low: "Laag",
    medium: "Gemiddeld",
    high: "Hoog",
    urgent: "Dringend",
    due_date: "Deadline",
    save: "Opslaan",
    invite_member: "Lid uitnodigen",
  },
};

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: "sys-btw",
    title: "BTW Aangifte",
    description: "Przygotowanie i wysłanie deklaracji VAT",
    priority: "high",
    category: "Tax",
  },
  {
    id: "sys-icp",
    title: "ICP Opgaaf",
    description: "Deklaracja transakcji wewnątrzwspólnotowych",
    priority: "medium",
    category: "Tax",
  },
  {
    id: "sys-loon",
    title: "Loonheffingen",
    description: "Miesięczne rozliczenie podatku od wynagrodzeń",
    priority: "high",
    category: "Payroll",
  },
  {
    id: "sys-ib",
    title: "Inkomstenbelasting",
    description: "Rozliczenie roczne podatku dochodowego",
    priority: "medium",
    category: "Tax",
  },
  {
    id: "sys-vpb",
    title: "Vennootschapsbelasting",
    description: "Podatek korporacyjny dla B.V.",
    priority: "low",
    category: "Audit",
  },
];

export const GROUP_COLORS = [
  "bg-blue-500",
  "bg-red-500",
  "bg-green-500",
  "bg-orange-500",
  "bg-purple-500",
  "bg-pink-500",
  "bg-indigo-500",
  "bg-teal-500",
];

export const BUSINESS_EMOJIS = [
  "💰",
  "💶",
  "💵",
  "💸",
  "💳",
  "🧾",
  "📊",
  "📉",
  "📈",
  "📋",
  "🖊️",
  "📅",
  "📂",
  "🗂️",
  "🏦",
  "⚖️",
  "📠",
  "💼",
  "💻",
  "🖨️",
  "🤝",
  "👍",
  "👎",
  "👏",
  "🤞",
  "🙏",
  "👀",
  "🧠",
  "💡",
  "🚀",
  "✅",
  "❌",
  "⚠️",
  "❗",
  "❓",
  "💯",
  "🎯",
  "📢",
  "🔔",
  "🔒",
];

export const STICKERS = [
  { id: "s1", label: "APPROVED", color: "bg-green-600", text: "✅ APPROVED" },
  { id: "s2", label: "PAID", color: "bg-blue-600", text: "💸 PAID" },
  { id: "s3", label: "URGENT", color: "bg-red-600", text: "🔥 URGENT" },
  { id: "s4", label: "REVIEW", color: "bg-orange-500", text: "👀 REVIEW" },
  { id: "s5", label: "DONE", color: "bg-emerald-500", text: "🎉 DONE" },
  { id: "s6", label: "THANKS", color: "bg-purple-500", text: "🙏 THANKS" },
];
