import { Language, QuoteTemplate, ResourceTemplate } from "./types";

export const LABELS = {
  [Language.PL]: {
    dashboard: "Panel Główny",
    newQuote: "Nowa Oferta",
    clients: "Klienci",
    settings: "Ustawienia",
    edit: "Edytuj",
    preview: "Podgląd / Druk",
    save: "Zapisz",
    aiHelp: "Ulepsz z AI",
    addItem: "Dodaj Pozycję",
    clientDetails: "Dane Klienta",
    projectDetails: "Szczegóły Projektu",
    workItems: "Zakres Prac",
    photos: "Dokumentacja Zdjęciowa",
    totalExcl: "Suma netto",
    totalIncl: "Suma brutto",
    generate: "Generuj",
    back: "Wróć",
    status: "Status",
    date: "Data",
    executionDate: "Data wykonania",
    reference: "Numer Ref.",
    subject: "Dotyczy (Betreft)",
    intro: "Tekst Wstępny",
    category: "Kategoria",
    desc: "Opis",
    qty: "Ilość",
    unit: "J.m.",
    price: "Cena j.",
    vat: "BTW (%)",
    uploadPhoto: "Dodaj Zdjęcie",
    drawMode: "Rysuj (X)",
    clear: "Wyczyść",
    templates: "Szablony",
    loadTemplate: "Wczytaj Szablon",
    saveAsTemplate: "Zapisz jako Szablon",
    templateName: "Nazwa szablonu",
    cancel: "Anuluj",
    useTemplate: "Użyj tego szablonu",
    // New Resource Labels
    tabQuote: "Oferta (Klient)",
    tabResources: "Zasoby (Materiały/Sprzęt)",
    materials: "Materiały (Materialen)",
    tools: "Sprzęt / Narzędzia (Materieel)",
    addMaterial: "Dodaj Materiał",
    addTool: "Dodaj Narzędzie",
    resourceName: "Nazwa Artykułu",
    internalUse: "Tylko do użytku wewnętrznego",
    cost: "Koszt j.",
    resourceTemplates: "Szablony Zasobów",
    loadResourceTemplate: "Wczytaj Zestaw",
    saveResourceTemplate: "Zapisz Zestaw",
    notesPlaceholder: "Dodaj uwagę do tej pozycji...",
    internalNotes: "Notatki Wewnętrzne / Uwagi do Realizacji", // Added
    // Financial Analysis
    financialAnalysis: "Analiza Rentowności",
    estimatedHours: "Szacowane Godziny",
    hourlyRate: "Twoja Stawka Bazowa (h)",
    projectRevenue: "Przychód z Oferty",
    projectCosts: "Koszty Materiałowe",
    laborCosts: "Twoja Wypłata (Czas)",
    totalProfit: "Ekstra Zysk (Marża)",
    margin: "Marża",
    riskBuffer: "Bufor Ryzyka (%)",
    riskCost: "Koszt Ryzyka",
    effectiveRate: "Efektywna Stawka/h",
    effectiveRateDesc:
      "Tyle realnie zarobisz na godzinę po odliczeniu materiałów i ryzyka.",
    rateWarning: "Uwaga: Zarabiasz mniej niż Twoja stawka bazowa!",
    goodJob: "Dobra robota! Rentowność wysoka.",
    totalEarnings: "Łącznie do kieszeni",
    totalEarningsDesc: "Wypłata za godziny + Ekstra Zysk",
    // Settings Labels
    companyProfile: "Profil Firmy",
    clientDatabase: "Baza Klientów",
    uploadLogo: "Wgraj Logo",
    companyName: "Nazwa Firmy",
    address: "Adres",
    city: "Miasto i Kod",
    bankDetails: "Dane Bankowe",
    addClient: "Dodaj Klienta",
    selectClient: "Wybierz Klienta",
    noClients: "Brak zapisanych klientów.",
    contactInfo: "Dane Kontaktowe",
    // Price Visibility
    showPrices: "Pokaż Ceny",
    hidePrices: "Ukryj Ceny",
  },
  [Language.NL]: {
    dashboard: "Dashboard",
    newQuote: "Nieuwe Offerte",
    clients: "Klanten",
    settings: "Instellingen",
    edit: "Bewerken",
    preview: "Voorbeeld",
    save: "Opslaan",
    aiHelp: "AI Hulp",
    addItem: "Regel toevoegen",
    clientDetails: "Klantgegevens",
    projectDetails: "Projectgegevens",
    workItems: "Werkzaamheden",
    photos: "Fotodocumentatie",
    totalExcl: "Totaal excl. BTW",
    totalIncl: "Totaal incl. BTW",
    generate: "Genereren",
    back: "Terug",
    status: "Status",
    date: "Datum",
    executionDate: "Uitvoerdatum",
    reference: "Kenmerk",
    subject: "Betreft",
    intro: "Inleiding",
    category: "Categorie",
    desc: "Omschrijving",
    qty: "Aantal",
    unit: "Eenh.",
    price: "Prijs",
    vat: "BTW",
    uploadPhoto: "Foto toevoegen",
    drawMode: "Tekenen",
    clear: "Wissen",
    templates: "Sjablonen",
    loadTemplate: "Sjabloon Laden",
    saveAsTemplate: "Opslaan als Sjabloon",
    templateName: "Sjabloonnaam",
    cancel: "Annuleren",
    useTemplate: "Gebruik dit sjabloon",
    // New Resource Labels
    tabQuote: "Offerte (Klant)",
    tabResources: "Resources (Intern)",
    materials: "Materialen",
    tools: "Materieel / Gereedschap",
    addMaterial: "Materiaal toevoegen",
    addTool: "Materieel toevoegen",
    resourceName: "Artikelnaam",
    internalUse: "Alleen voor intern gebruik",
    cost: "Kostprijs",
    resourceTemplates: "Resource Sjablonen",
    loadResourceTemplate: "Set Laden",
    saveResourceTemplate: "Set Opslaan",
    notesPlaceholder: "Voeg notitie toe...",
    internalNotes: "Interne Notities / Uitvoeringsinstructies", // Added
    // Financial Analysis
    financialAnalysis: "Winstgevendheidsanalyse",
    estimatedHours: "Geschatte Uren",
    hourlyRate: "Jouw Uurtarief (Basis)",
    projectRevenue: "Omzet Offerte",
    projectCosts: "Materiaalkosten",
    laborCosts: "Jouw Salaris (Uren)",
    totalProfit: "Extra Winst (Marge)",
    margin: "Marge",
    riskBuffer: "Risico Buffer (%)",
    riskCost: "Onvoorziene Kosten",
    effectiveRate: "Effectief Uurtarief",
    effectiveRateDesc:
      "Dit verdien je per uur na aftrek van materiaal en risico.",
    rateWarning: "Let op: Je verdient minder dan je basistarief!",
    goodJob: "Goed bezig! Hoge winstgevendheid.",
    totalEarnings: "Totaal Verdiensten",
    totalEarningsDesc: "Salaris + Winst",
    // Settings Labels
    companyProfile: "Bedrijfsprofiel",
    clientDatabase: "Klantenbestand",
    uploadLogo: "Logo Uploaden",
    companyName: "Bedrijfsnaam",
    address: "Adres",
    city: "Stad & Postcode",
    bankDetails: "Bankgegevens",
    addClient: "Klant toevoegen",
    selectClient: "Klant selecteren",
    noClients: "Geen klanten opgeslagen.",
    contactInfo: "Contactgegevens",
    // Price Visibility
    showPrices: "Prijzen Tonen",
    hidePrices: "Prijzen Verbergen",
  },
};

export const DEFAULT_INTRO_NL = `Geachte heer/mevrouw,\n\nNaar aanleiding van uw aanvraag doen wij u hierbij een passende aanbieding toekomen voor de uit te voeren werkzaamheden.`;

export const UNITS = [
  "m1",
  "m2",
  "stuks",
  "post",
  "uur",
  "kg",
  "ltr",
  "zak",
  "blik",
];

// Szablony zasobów są teraz przechowywane w bazie Supabase (tabela: resource_templates)
// Każdy użytkownik ma własne szablony, można je również oznaczać jako publiczne
export const INITIAL_RESOURCE_TEMPLATES: ResourceTemplate[] = [];

// Szablony ofert są teraz przechowywane w bazie Supabase (tabela: quote_templates)
// Każdy użytkownik ma własne szablony, można je również oznaczać jako publiczne
export const INITIAL_TEMPLATES: QuoteTemplate[] = [];
